### ISSUE TITLE
Not compatible with Debian 10

### ISSUE THREAD

**Issue by gabviv73** [cirrax/puppet-postfixadmin#1]
Php 7.3 has not mysql dbtype.
Have to use mysqli

````
# bash /usr/share/postfixadmin/scripts/postfixadmin-cli admin add admin@rvmgroup.it --password thepass --password2 thepass --superadmin

<p />DEBUG INFORMATION:<br />MySQL 3.x / 4.0 functions not available! (php5-mysql installed?)<br />database_type = 'mysql' in config.inc.php, are you using a different database? 
    <p />
    Please check the documentation and website for more information.
    <p />
    <a href="http://postfixadmin.sf.net/">Postfix Admin</a><br />
    <a href='https://sourceforge.net/p/postfixadmin/discussion/676076'>Forums</a>
````

Virtualhost is wrong:

````
The Postfix Admin directory layout changed.

Please update your webserver config so that the DocumentRoot or Alias points to the directory "public".
````

**Comment by gabviv73** [comment]
Forked and fixed. I'm not a developer, if you want to check my fork ...

**Comment by trefzer** [comment]
I had a quick look. I would be happy If we could use a module specific hiera.yaml to fix and get rid of params.pp. But I need some time to do that.
The commit af76345c252f617d08b7d344f7b726ed357739fe (Fixes ssl vhost bug) I cannot understand, seems to be unessesary.

For the Readme: I will definitily include the example, but not the file hiera.yaml since this is found in the general puppet documentation and not module specific. Actually anybody having more than one specific node will have a more complex hiera.yaml file.

**Comment by gabviv73** [comment]
> The commit [af76345](https://github.com/cirrax/puppet-postfixadmin/commit/af76345c252f617d08b7d344f7b726ed357739fe) (Fixes ssl vhost bug) I cannot understand, seems to be unessesary.

If not ssl, we get a vhost that listen on port 443 without ssl certs.

> For the Readme: I will definitily include the example, but not the file hiera.yaml since this is found in the general puppet documentation and not module specific. Actually anybody having more than one specific node will have a more complex hiera.yaml file.

I agree, I never used hiera, so I included everything for my reference ...

**Comment by trefzer** [comment]
ok now I see the difference in the if/else for ssl. But I would prefer a parameter for the port. So you can set it to whatever you like.
I never thought of someone using it without ssl ;)
can you make a pull request for that, then I will merge it.

For the Readme, you could also make one.

And one for 867fc5243391e404e808279785ba9045ec0aee15 you can make one, I will also merge, with an additional spec test.

Other question, what is /usr/share/postfixadmin/templates_c is this debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926253 ?
If so, I prefer to have it fixed in the package. But not in the puppet module. If you insist on fixing in the puppet module, make a separate class (eg. postfixadmin::debian_buster_fix) which one could include if prefered. This is because some people may use a custom package which already fixed this bug.

For the parameters, I will then add a proper hiera.yaml file and a data directory.

Is this possible ?

**Comment by gabviv73** [comment]
Created a PR. I'm new to this, sorry if it's not correct.

**Comment by gabviv73** [comment]
> Other question, what is /usr/share/postfixadmin/templates_c is this debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926253 ?

The folder is missing. The bug is not fixed since a long time ...

**Comment by trefzer** [comment]
actually the debian bugfix is already available in the module ;) 
you just have to include the class postfixadmin::fix_debian_bug (forgot about that one :)

About PR: thanks, I thought to make separate ones (this is easier for discussions, and also for merging, but it's ok, I will cherry pick :))
 
btw. also for the issue it's easier to make separate ones (we are already discussing 3 subjects here: debian bug, ssl and buster compatibility !)

**Comment by gabviv73** [comment]
> actually the debian bugfix is already available in the module ;)
> you just have to include the class postfixadmin::fix_debian_bug (forgot about that one :)

Maybe it's useful to enable the inclusion automatically based on a fact like codename ?

> About PR: thanks, I thought to make separate ones (this is easier for discussions, and also for merging, but it's ok, I will cherry pick :))

I will learn about PR :-)

> btw. also for the issue it's easier to make separate ones (we are already discussing 3 subjects here: debian bug, ssl and buster compatibility !)

I agree, next time I will be more tidy :-)

**Comment by trefzer** [comment]
Hopefully I merged everything now !
Otherwise pleas open a new issue !
Thanks.
